' Developer Express Code Central Example:
' How to merge cells in the GridControl
' 
' This example demonstrates how to achieve the merged cells effect in the
' GridControl. The main idea consists of stretching the top merged cell and
' showing it over other merged cells. For this purpose, the Panel.ZIndex and
' Margin properties are used.
' Please take special note that this example doesn't
' support editing cells. This example is designed for the DeepBlue theme and may
' need to be modified if you wish to use it in other themes.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4614

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
